### ISSUE TITLE
Node.js Error: connectToDatabase is not defined

### ISSUE THREAD

**Issue by chakany** [Pik-9/schluessel#4]
I have everything installed, this is the error:
 ```
const dbConnection = connectToDatabase(
                     ^

ReferenceError: connectToDatabase is not defined
    at Object.<anonymous> (C:\Users\jackc\Desktop\Blade\index.js:9:22)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```

This is my code:
```
const myCredentials = require('schluessel');

const dbConnection = connectToDatabase(
    myCredentials.database.username,
    myCredentials.database.password
);
```
Any idea on how to fix?

**Comment by Pik-9** [comment]
Hi @realshapes,

the method `connectToDatabase` was just an **example** to illustrate how one _could_ use `schluessel`, but is not part of the package.

If you just want to get a glimpse of the basic functioning of this package, just do:
```javascript
const myCredentials = require('schluessel');
console.dir(myCredentials);
```

This will dump whatever you put into your credentials file beforehand.

Regards,
🂩
