### ISSUE TITLE
Store key in System Environment is not working

### ISSUE THREAD

**Issue by paulp88** [Pik-9/schluessel#5]
Hi!

I want to store my key in the System Environment variables. I thought that if set there NODE_MASTER_KEY with my key, it will be enough, but it seems that I should copy the key file to the server. Should I do something else?

Error: The key file could not be found.
    at loadKeyFromFile (D:\App\node_modules\schluessel\src\cred.js:17:11)
    at loadKey (D:\App\node_modules\schluessel\src\cred.js:51:43)
    at Object.loadVault (D:\App\node_modules\schluessel\src\cred.js:73:15)
    at Object.<anonymous> (D:\App\node_modules\schluessel\index.js:9:34)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at Module.Hook._require.Module.require (C:\Users\AppData\Roaming\npm\node_modules\pm2\node_modules\require-in-the-middle\index.js:70:39)

**Comment by paulp88** [comment]
I solved this by restarting the server.
